### ISSUE TITLE
SSL mode verify-ca not supported

### ISSUE THREAD

**Issue by Lynnes001** [faisaltheparttimecoder/mock-data#40]
I was trying to connect to my remote server. with --uri command

`--uri postgres://uname:pwd@localhost:port/db?ssl=true&sslmode=verify-ca&sslrootcert=localpathtosslca`

at first it says `err: pg: options other than 'sslmode' and 'application_name' are not supported`

then i removed `ssl=true&`, if says `err: pg: sslmode 'verify-ca' is not supported`

So is it really not a valid feature in this tool? since `go-pg` seems support it. thanks.

**Comment by faisaltheparttimecoder** [comment]
Seems like it was added on v10 of `go-pg` and we are using v8. 

https://github.com/go-pg/pg/commit/0a549f85c0a26507f6489a7af6d783daf03cd22a

Will need to upgrade the go-pg package to v10. Thanks for reporting

**Comment by faisaltheparttimecoder** [comment]
fixed in v2.9

**Comment by Lynnes001** [comment]
Hi, 

It seems the problem still exist in another way? Sorry for a ugly-looking blue pen. Would you please take a look? Thanks.

![Capture](https://user-images.githubusercontent.com/16166734/116034799-7a2ce580-a696-11eb-844d-865da854f9a3.PNG)

**Comment by faisaltheparttimecoder** [comment]
As the error suggest, `go-pg` only supports `sslmode`, `application_name` & `connection_timeout` as the query parameters

https://github.com/go-pg/pg/blob/v10/options.go#L223-L258

It seems like earlier back in v3 or so, it did support it.

https://github.com/go-pg/pg/pull/284/files#diff-4eec45b6a922746411c0f8aea183e30f77af1b0a5bea1688eaf343a5f9c23703R23

and it was deprecaited, for `TlsConfig`

https://github.com/go-pg/pg/blob/v10/options.go#L24

so ya, you will need to remove the `ssl` flag
